name: Build and release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [2.7, 3.6]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ github.sha }}

      - name: Install python dependencies
        uses: ./.github/actions/install-python-dependencies

      - name: Show python dependencies
        run: pip freeze

      - name: Run tests
        uses: ./.github/actions/run-tests

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.test_number }}

  Coveralls:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  Release:
    if: ${{ github.event_name == 'push' }}
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Cache Python Dependencies
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-2.7-${{ github.sha }}

      - name: Install python dependencies
        uses: ./.github/actions/install-python-dependencies

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
