name: Build and release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python: python3
            pip: pip3
          - python: python2
            pip: pip

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Python
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ github.sha }}

      - name: Install python dependencies
        run: |
          ${{ matrix.pip }} install --user --upgrade pip
          ${{ matrix.pip }} --no-cache-dir install --user setuptools wheel "urllib3==1.25.11"
          ${{ matrix.pip }} --no-cache-dir install --user -r requirements.txt

      - name: Show python dependencies
          ${{ matrix.python }} --version
          ${{ matrix.pip }} freeze

      - name: Run tests
        uses: ./.github/actions/run-tests

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.test_number }}

  Coveralls:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  Release:
    if: ${{ github.event_name == 'push' }}
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Cache Python Dependencies
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-2.7-${{ github.sha }}

      - name: Install python dependencies
        uses: ./.github/actions/install-python-dependencies

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
